name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build:production

      - name: Set permissions on target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Ensuring correct permissions on target directory..."
            sudo mkdir -p /home/ec2-user/iteletric-app
            sudo chown -R ec2-user:ec2-user /home/ec2-user/iteletric-app
            sudo chmod -R 755 /home/ec2-user/iteletric-app

      - name: Clean target directory on Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Cleaning target directory..."
            sudo rm -rf /home/ec2-user/iteletric-app/*

      - name: Copy files to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "dist/iteletric-app/**/*"
          target: "/home/ec2-user/iteletric-app"

      - name: Set correct permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Setting correct permissions..."
            sudo chmod -R 755 /home/ec2-user/iteletric-app
            sudo chown -R nginx:nginx /home/ec2-user/iteletric-app

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Restarting Nginx..."
            sudo systemctl restart nginx

      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Verifying deployment..."
            curl -I http://localhost